on:
  push:
    branches:
      - 'main'
    # tags:
    #   - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Environment
        uses: actions/checkout@v3
      - name: Setup Node Environment
        uses: actions/setup-node@v3
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - run: |
          mkdir -p wp-minyan-times/build/
      - name: Bundle server files
        run: |
          cp -r services block.json index.php wp-minyan-times/
      - name: Bundle js buid
        run: |
          cp -r build wp-minyan-times/build/
      - name: Zip Assets
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r wp-minyan-times.zip wp-minyan-times
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build.zip
          asset_name: wp-minyan-times.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: 'Latest version'
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
